### ISSUE TITLE
Update to use jsreport 2.0 in .NET as binary

### ISSUE THREAD

**Issue by WdeBruin** [jsreport/jsreport-dotnet-types#4]
Just wondering about updating the .NET package for binary to jsreport 2.0.
What changes would be required?

See https://jsreport.net/blog/jsreport-v2-released , new features.

**Comment by pofider** [comment]
Please subscribe here.  I have it in queue. Just terribly busy at this moment.  But I get to it soon.
https://github.com/jsreport/jsreport-dotnet/issues/21
