### ISSUE TITLE
Missing 'Merge whole document' for PdfOperation?

### ISSUE THREAD

**Issue by robyvandamme** [jsreport/jsreport-dotnet-types#5]
The 'Merge whole document' option seems to be missing for PdfOperation?

**Comment by pofider** [comment]
It is. I will have to update types to match the latest release.
Until then you can always send just an anonymous object instead.

**Comment by pofider** [comment]
You can now update deps - mainly jsreport.Types@2.4.0 and jsreport.Binary@2.4.0 to have type support for `merge whole document`.
